### ISSUE TITLE
Chapter_1/practise/4_8/findEqual.hpp has some error

### ISSUE THREAD

**Issue by S1xe** [Spdwal/Algorithms#2]
If the vector contains multiple duplicate values(e.g. 0 0 0 0), your funtions will return different values.
```c++
    vector<int> ivec{0, 0, 0, 0};
    cout << findEqual(ivec) << endl;     // 6
    cout << findEqualFast(ivec) << endl; // 3
```

Also,the function `findEqualFast` can't work fine if the vector is empty.
>  int flag = vec[0];

**Comment by Spdwal** [comment]
emmmmm It was sloved and fotgot to close the issue LOL
