### ISSUE TITLE
The function declare error

### ISSUE THREAD

**Issue by S1xe** [Spdwal/Algorithms#3]
https://github.com/Spdwal/Algorithms/blob/805c99fa5ca7cf53c1c41cf7360e0a8647425346/Chapter_1/practise/1_22/main.cpp#L6

What does `const vecg++ tor<int> &ivec` mean?

**Comment by Spdwal** [comment]
get it

**Comment by S1xe** [comment]
close at 64e7aaba7cf9841bb520e65fa095e5f914e2ef28
