### ISSUE TITLE
What will happen if `num` is less than zero

### ISSUE THREAD

**Issue by S1xe** [Spdwal/Algorithms#4]
https://github.com/Spdwal/Algorithms/blob/805c99fa5ca7cf53c1c41cf7360e0a8647425346/Chapter_1/practise/1_14/lg.hpp#L2-L12

If the `num` is less than zero,your function `lg` doesn't report an error or return a default value as error code

**Comment by Spdwal** [comment]
add an error exception

**Comment by S1xe** [comment]
close at 6114e93e7dffd39692cf199fdea574b1bdc9e064
